apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: proxy
data:
  default.conf: |
    resolver kube-dns.kube-system.svc.cluster.local valid=60s ipv6=off;

    server {
      listen            80;
      server_name       0.0.0.0;
      keepalive_timeout 15;

      location / {
        set $upsteam http://gateway.default.svc.cluster.local:8080;

        proxy_pass       $upsteam;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # return 301 https://$host$request_uri;
    }

    server {
      listen            443;
      server_name       0.0.0.0;
      keepalive_timeout 300;

      ssl_protocols              TLSv1.2;
      ssl_prefer_server_ciphers  on;
      ssl_certificate            /etc/nginx/cert/cert.pem;
      ssl_certificate_key        /etc/nginx/cert/privkey.pem;

      location / {
        set $upsteam http://gateway.default.svc.cluster.local:8080;

        proxy_pass       $upsteam;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
