version: '3.8'

services:
  # Database
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build:
      context: ./infra/docker/infra/mysql
      dockerfile: Dockerfile.test
    volumes:
      - ./infra/mysql/test.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/sql:/docker-entrypoint-initdb.d # 完了検知が難しいので手動で
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -p12345678

  # Other
  proto:
    container_name: proto
    build:
      context: ./infra/docker/proto
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/calmato/gran-book/proto
    volumes:
      - ./api:/go/src/github.com/calmato/gran-book/api:cached
      - ./proto:/go/src/github.com/calmato/gran-book/proto:cached

  wait:
    image: willwill/wait-for-it:latest
    depends_on:
      mysql:
        condition: service_healthy
