version: '3.8'

services:
  # Database
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build:
      context: ./infra/docker/infra/mysql
      dockerfile: Dockerfile.test
    volumes:
      - ./infra/mysql/ci.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3306:3306

  firebase:
    container_name: firebase
    build:
      context: ./infra/docker/infra/firebase
      dockerfile: Dockerfile
    working_dir: /var/firebase
    volumes:
      - ./infra/firebase:/var/firebase:cached
    ports:
      - 4000:4000
      - 9090:8080
      - 9099:9099

  # Other
  proto:
    container_name: proto
    build:
      context: ./infra/docker/proto
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/calmato/gran-book/proto
    volumes:
      - ./native:/go/src/github.com/calmato/gran-book/native:cached
      - ./web:/go/src/github.com/calmato/gran-book/web:cached
      - ./proto:/go/src/github.com/calmato/gran-book/proto:cached

  wait:
    image: willwill/wait-for-it:latest
