version: '3.8'

services:
  # Frontend
  admin:
    container_name: gran_book_admin
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile_development
    working_dir: /var/web/admin
    volumes:
      - ./web/admin:/var/web/admin:cached
    ports:
      - 3000:3000
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    command: yarn dev -H 0.0.0.0 -p 3000

  # Backend
  envoy:
    container_name: gran_book_envoy
    build:
      context: ./infra/docker/infra/envoy
      dockerfile: Dockerfile_development
    volumes:
      - ./infra/envoy/development.yaml:/etc/envoy/envoy.yaml:cached
      - ./tmp/logs/envoy:/var/log:delegated
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - api
    command: envoy -c /etc/envoy/envoy.yaml

  # Monitoring

networks:
  api: {}
  monitoring: {}
