version: '3.8'

services:
  # Frontend
  native:
    container_name: gran_book_native
    build:
      context: ./infra/docker/native
      dockerfile: Dockerfile_development
    working_dir: /var/native
    volumes:
      - ./native:/var/native:cached

  admin:
    container_name: gran_book_admin
    build:
      context: ./infra/docker/web/admin
      dockerfile: Dockerfile_development
    working_dir: /var/web/admin
    volumes:
      - ./web/admin:/var/web/admin:cached
    ports:
      - 3000:3000
    environment:
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
    command: yarn dev -H 0.0.0.0 -p 3000

  # Backend
  gateway:
    container_name: gran_book_gateway
    build:
      context: ./infra/docker/infra/gateway
      dockerfile: Dockerfile_development
    volumes:
      - ./infra/gateway:/go/src/github.com/calmato/gran-book/infra/gateway:cached
    ports:
      - 8080:8080
    networks:
      - api

  # Monitoring

networks:
  api: {}
  monitoring: {}
