// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interface/validation/chat.go

// Package mock_validation is a generated GoMock package.
package mock_validation

import (
	reflect "reflect"

	proto "github.com/calmato/gran-book/api/server/user/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockChatRequestValidation is a mock of ChatRequestValidation interface.
type MockChatRequestValidation struct {
	ctrl     *gomock.Controller
	recorder *MockChatRequestValidationMockRecorder
}

// MockChatRequestValidationMockRecorder is the mock recorder for MockChatRequestValidation.
type MockChatRequestValidationMockRecorder struct {
	mock *MockChatRequestValidation
}

// NewMockChatRequestValidation creates a new mock instance.
func NewMockChatRequestValidation(ctrl *gomock.Controller) *MockChatRequestValidation {
	mock := &MockChatRequestValidation{ctrl: ctrl}
	mock.recorder = &MockChatRequestValidationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatRequestValidation) EXPECT() *MockChatRequestValidationMockRecorder {
	return m.recorder
}

// CreateChatMessage mocks base method.
func (m *MockChatRequestValidation) CreateChatMessage(req *proto.CreateChatMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatMessage", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChatMessage indicates an expected call of CreateChatMessage.
func (mr *MockChatRequestValidationMockRecorder) CreateChatMessage(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatMessage", reflect.TypeOf((*MockChatRequestValidation)(nil).CreateChatMessage), req)
}

// CreateChatRoom mocks base method.
func (m *MockChatRequestValidation) CreateChatRoom(req *proto.CreateChatRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChatRoom", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChatRoom indicates an expected call of CreateChatRoom.
func (mr *MockChatRequestValidationMockRecorder) CreateChatRoom(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChatRoom", reflect.TypeOf((*MockChatRequestValidation)(nil).CreateChatRoom), req)
}

// ListChatRoom mocks base method.
func (m *MockChatRequestValidation) ListChatRoom(req *proto.ListChatRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatRoom", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListChatRoom indicates an expected call of ListChatRoom.
func (mr *MockChatRequestValidationMockRecorder) ListChatRoom(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatRoom", reflect.TypeOf((*MockChatRequestValidation)(nil).ListChatRoom), req)
}

// UploadChatImage mocks base method.
func (m *MockChatRequestValidation) UploadChatImage(req *proto.UploadChatImageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadChatImage", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadChatImage indicates an expected call of UploadChatImage.
func (mr *MockChatRequestValidationMockRecorder) UploadChatImage(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadChatImage", reflect.TypeOf((*MockChatRequestValidation)(nil).UploadChatImage), req)
}
