settings:
  legacy:
    force: true
    interval: 0s
  resources:
    outputs: '/var/log/gateway/outputs.log'
    logs: '/var/log/gateway/stdout.log'
    errors: '/var/log/gateway/errors.log'

schema:
  - name: gateway
    path: .
    commands:
      install:
        status: true
        method: go build -o app ./cmd/main.go
      run:
        status: true
        method: ./app
    watcher:
      paths:
        - .
      ignore_paths:
        - .gitignore
        - .golangci.yaml
        - go.mod
        - go.sum
        - Makefile
      extensions:
        - go
