// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go

// Package mock_validation is a generated GoMock package.
package mock_validation

import (
	reflect "reflect"

	information "github.com/calmato/gran-book/api/proto/information"
	gomock "github.com/golang/mock/gomock"
)

// MockInquiryRequestValidation is a mock of InquiryRequestValidation interface.
type MockInquiryRequestValidation struct {
	ctrl     *gomock.Controller
	recorder *MockInquiryRequestValidationMockRecorder
}

// MockInquiryRequestValidationMockRecorder is the mock recorder for MockInquiryRequestValidation.
type MockInquiryRequestValidationMockRecorder struct {
	mock *MockInquiryRequestValidation
}

// NewMockInquiryRequestValidation creates a new mock instance.
func NewMockInquiryRequestValidation(ctrl *gomock.Controller) *MockInquiryRequestValidation {
	mock := &MockInquiryRequestValidation{ctrl: ctrl}
	mock.recorder = &MockInquiryRequestValidationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInquiryRequestValidation) EXPECT() *MockInquiryRequestValidationMockRecorder {
	return m.recorder
}

// CreateInquiry mocks base method.
func (m *MockInquiryRequestValidation) CreateInquiry(req *information.CreateInquiryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInquiry", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInquiry indicates an expected call of CreateInquiry.
func (mr *MockInquiryRequestValidationMockRecorder) CreateInquiry(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInquiry", reflect.TypeOf((*MockInquiryRequestValidation)(nil).CreateInquiry), req)
}
