apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: gateway
data:
  default.conf: |
    resolver kube-dns.kube-system.svc.cluster.local valid=60s ipv6=off;

    client_max_body_size    100M;
    client_body_buffer_size 100M;
    proxy_request_buffering off;

    server {
      listen            80;
      server_name       0.0.0.0;
      keepalive_timeout 15;

      return 301 https://$host$request_uri;
    }

    server {
      listen            443 ssl;
      server_name       0.0.0.0;
      keepalive_timeout 300;

      ssl_protocols              TLSv1.2;
      ssl_prefer_server_ciphers  on;
      ssl_certificate            /etc/tls/cert.pem;
      ssl_certificate_key        /etc/tls/privkey.pem;

      location / {
        set $upsteam http://native-gateway.default.svc.cluster.local:8080;

        proxy_pass       $upsteam;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /admin {
        set $upsteam http://admin-gateway.default.svc.cluster.local:8080;

        proxy_pass       $upsteam;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        rewrite /admin/(.*)$ /$1 break;
      }

      location /health {
        access_log off;
        return     200;
      }
    }
