apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gateway
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: gran-book-stg-node
      tolerations:
      - key: gran-book-stg-node
        operator: Equal
        value: ingress
        effect: NoSchedule
      priorityClassName: high-priority
      containers:
      - name: nginx
        image: nginx:1.19.6-alpine
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
        ports:
        - name: http
          hostPort: 80
          containerPort: 80
        - name: https
          hostPort: 443
          containerPort: 443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/tls
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        env:
        - name: TZ
          value: 'Asia/Tokyo'
      volumes:
      - name: tls-certs
        secret:
          secretName: nginx-secret
      - name: nginx-conf
        configMap:
          name: nginx-config
