settings:
  legacy:
    force: true
    interval: 0s
  files:
    outputs:
      status: false
    logs:
      status: false
    errors:
      status: false

schema:
  - name: book_api
    path: .
    commands:
      install:
        status: true
        method: go build -o app ./cmd/main.go
      run:
        status: true
        method: ./app
    watcher:
      paths:
        - .
      ignore_paths:
        - .gitignore
        - .golangci.yaml
        - go.mod
        - go.sum
        - Makefile
      extensions:
        - go
