openapi: 3.0.0
info:
  title: Gran Book (Admin)
  description: 管理コンソール用API
  version: 0.5.0
servers:
  - url: http://localhost:8081
    description: 開発環境
  - url: https://api.gran-book-stg.calmato.work/admin
    description: 検証環境
paths:
  /v1/auth:
    get:
      summary: 認証情報取得
      tags:
        - AuthService
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/auth/email:
    patch:
      summary: メールアドレス更新
      tags:
        - AuthService
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAuthEmailRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/auth/password:
    patch:
      summary: パスワード更新
      tags:
        - AuthService
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAuthPasswordRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/auth/profile:
    patch:
      summary: ユーザ情報更新
      tags:
        - AuthService
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAuthProfileRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/auth/thumbnail:
    post:
      summary: サムネイルアップロード
      tags:
        - AuthService
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadAuthThumbnailRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authThumbnailResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin:
    get:
      summary: 管理者一覧
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: 取得上限数
        - in: query
          name: offset
          schema:
            type: integer
          required: false
          description: 取得開始位置
        - in: query
          name: field
          schema:
            type: string
          required: false
          description: 検索項目
        - in: query
          name: value
          schema:
            type: string
          required: false
          description: 検索値
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminListResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    post:
      summary: 管理者登録
      tags:
        - AdminService
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAdminRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin/{userId}:
    get:
      summary: 管理者取得
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
    delete:
      summary: 管理者削除
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/emptyResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin/{userId}/role:
    patch:
      summary: 管理者権限更新
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAdminRoleRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin/{userId}/password:
    patch:
      summary: 管理者パスワード更新
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAdminPasswordRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin/{userId}/profile:
    patch:
      summary: 管理者プロフィール更新
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateAdminProfileRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /v1/admin/{userId}/thumbnail:
    post:
      summary: 管理者サムネイルアップロード
      tags:
        - AdminService
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ユーザーID
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/uploadAdminThumbnailRequest'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/adminThumbnailResponse'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
tags:
  - name: AuthService
    description: 認証関連
  - name: AdminService
    description: 管理者関連
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    # Request - Auth
    updateAuthEmailRequest:
      type: object
      properties:
        email:
          type: string
    updateAuthPasswordRequest:
      type: object
      properties:
        password:
          type: string
        passwordConfirmation:
          type: string
    updateAuthProfileRequest:
      type: object
      properties:
        username:
          type: string
        thumbnailUrl:
          type: string
          format: byte
        selfIntroduction:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
        phoneNumber:
          type: string
    uploadAuthThumbnailRequest:
      type: object
      properties:
        thumbnail:
          type: string
          format: binary
    # Request - Admin
    createAdminRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        passwordConfirmation:
          type: string
        role:
          type: integer
          format: int32
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
    updateAdminRoleRequest:
      type: object
      properties:
        role:
          type: integer
          format: int32
    updateAdminPasswordRequest:
      type: object
      properties:
        password:
          type: string
        passwordConfirmation:
          type: string
    updateAdminProfileRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
    uploadAdminThumbnailRequest:
      type: object
      properties:
        thumbnail:
          type: string
          format: binary
    # Response - Auth
    authResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        role:
          type: integer
          format: int32
        thumbnailUrl:
          type: string
        selfIntroduction:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    # Response - Admin
    adminResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        role:
          type: integer
          format: int32
        thumbnailUrl:
          type: string
        selfIntroduction:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    adminListResponse:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              username:
                type: string
              email:
                type: string
              phoneNumber:
                type: string
              role:
                type: integer
                format: int32
              thumbnailUrl:
                type: string
              selfIntroduction:
                type: string
              lastName:
                type: string
              firstName:
                type: string
              lastNameKana:
                type: string
              firstNameKana:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
        limit:
          type: integer
          format: int64
        offset:
          type: integer
          format: int64
        total:
          type: integer
          format: int64
        order:
          type: object
          properties:
            by:
              type: string
            direction:
              type: string
    adminThumbnailResponse:
      type: object
      properties:
        thumbnailUrl:
          type: string
    # Response - Error
    emptyResponse:
      type: object
    errorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: integer
          format: int32
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              reason:
                type: string
