openapi: 3.0.0
info:
  title: Gran Book
  version: "0.2.0"
servers:
  - url: http://localhost:8080
    description: 開発環境
  - url: https://api.gran-book-stg.calmato.work
    description: 検証環境
paths:
  /v1/auth:
    get:
      operationId: AuthService_GetAuth
      summary: 認証情報取得
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      tags:
        - AuthService
    post:
      operationId: AuthService_CreateAuth
      summary: ユーザ登録
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/protoCreateAuthRequest"
        required: true
      tags:
        - AuthService
  /v1/auth/address:
    patch:
      operationId: AuthService_UpdateAuthAddress
      summary: 住所更新
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/protoUpdateAuthAddressRequest"
        required: true
      tags:
        - AuthService
  /v1/auth/email:
    patch:
      operationId: AuthService_UpdateAuthEmail
      summary: メールアドレス変更
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/protoUpdateAuthEmailRequest"
        required: true
      tags:
        - AuthService
  /v1/auth/password:
    patch:
      operationId: AuthService_UpdateAuthPassword
      summary: メール認証用のパスワード変更
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/protoUpdateAuthPasswordRequest"
        required: true
      tags:
        - AuthService
  /v1/auth/profile:
    patch:
      operationId: AuthService_UpdateAuthProfile
      summary: プロフィール更新
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/protoAuthResponse"
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/rpcStatus"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/protoUpdateAuthProfileRequest"
        required: true
      tags:
        - AuthService
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    protoAuthResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        gender:
          type: integer
          format: int32
        email:
          type: string
        phoneNumber:
          type: string
        role:
          type: integer
          format: int32
        thumbnailUrl:
          type: string
        selfIntroduction:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
        postalCode:
          type: string
        prefecture:
          type: string
        city:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    protoCreateAuthRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        passwordConfirmation:
          type: string
    protoUpdateAuthAddressRequest:
      type: object
      properties:
        lastName:
          type: string
        firstName:
          type: string
        lastNameKana:
          type: string
        firstNameKana:
          type: string
        phoneNumber:
          type: string
        postalCode:
          type: string
        prefecture:
          type: string
        city:
          type: string
        addressLine1:
          type: string
        addressLine2:
          type: string
    protoUpdateAuthEmailRequest:
      type: object
      properties:
        email:
          type: string
    protoUpdateAuthPasswordRequest:
      type: object
      properties:
        password:
          type: string
        passwordConfirmation:
          type: string
    protoUpdateAuthProfileRequest:
      type: object
      properties:
        username:
          type: string
        gender:
          type: integer
          format: int32
        thumbnail:
          type: string
        selfIntroduction:
          type: string
    protobufAny:
      type: object
      properties:
        typeUrl:
          type: string
        value:
          type: string
          format: byte
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: "#/components/schemas/protobufAny"
