export { default as common } from './common'
export { default as v1Admin } from './v1/admin'
export { default as v1Auth } from './v1/auth'
export { default as v1Book } from './v1/book'
export { default as v1User } from './v1/user'
