#cloud-config

hostname: gran-book-vm
timezone: Asia/Tokyo
locale: en_US.utf8

disable_root: false

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - bash-completion
  - bind-utils
  - chrony
  - containerd.io
  - docker-ce
  - docker-ce-cli
  - epel-release
  - git
  - jq
  - make
  - net-tools
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - yum-utils

yum_repos:
  docker-ce-stable:
    name: Docker CE Stable - x86_64
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: 1
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-stable-source:
    name: Docker CE Stable - Sources
    baseurl: https://download.docker.com/linux/centos/$releasever/source/stable
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-nightly:
    name: Docker CE Nightly - x86_64
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/nightly
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg
  docker-ce-nightly-source:
    name: Docker CE Nightly - Sources
    baseurl: https://download.docker.com/linux/centos/$releasever/source/nightly
    enabled: 0
    gpgcheck: 1
    gpgkey: https://download.docker.com/linux/centos/gpg

write_files:
  - path: /etc/sysctl.conf
    append: true
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
  - path: /etc/dhcp/dhclient.conf
    owner: root:root
    permissions: '0755'
    content: |
      supersede domain-name-servers 1.1.1.1 8.8.8.8;
  - path: /etc/chrony.conf
    append: true
    content: |
      server ntp1.jst.mfeed.ad.jp iburst
      server ntp2.jst.mfeed.ad.jp iburst
      server ntp3.jst.mfeed.ad.jp iburst
      port 0

runcmd:
  - sed -i "s/\(^SELINUX=\).*$/\1disabled/" /etc/selinux/config
  - curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - git clone https://github.com/calmato/gran-book.git /var/gran-book
  - cd /var/gran-book && make setup
  - systemctl disable --now firewalld
  - systemctl disable --now postfix
  - systemctl enable --now chrony
  - systemctl enable --now docker
