apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: gran-book
    service: users
spec:
  selector:
    app: user-api
  # type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
    targetPort: 8080
