apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeip-serviceaccount
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeip-serviceaccount
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeip-serviceaccount
subjects:
  - kind: ServiceAccount
    name: kubeip-serviceaccount
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubeip-serviceaccount
  apiGroup: rbac.authorization.k8s.io
