name: Frontend(Admin) Deploy

on:
  push:
    paths:
      - '.github/workflows/cd-admin-for-master.yaml'
      - 'web/admin/**'
    branches:
      - master

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  FIREBASE_API_KEY: ${{ secrets.STG_FIREBASE_API_KEY }}
  FIREBASE_PROJECT_ID: ${{ secrets.STG_FIREBASE_PROJECT_ID }}
  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.STG_FIREBASE_MESSAGING_SENDER_ID }}
  API_URL: ${{ secrets.STG_ADMIN_API_URL }}

jobs:
  deploy_for_staging:
    name: Deploy for Staging
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./web/admin

    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        node: [16.1]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn config get cacheFolder)"
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Protoc
        run: yarn protoc

      - name: Build
        run: yarn generate

      - name: Install firebase-tools
        run: yarn global add firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          firebase use staging
          firebase deploy --only hosting:staging --token ${FIREBASE_TOKEN}
