name: Backend(Book API) Build and Test
on:
  push:
    paths:
      - '.github/workflows/ci-book-api-for-all.yaml'
      - 'api/server/book/**'

env:
  PROTOBUF_VERSION: 3.9.0
  PROTOTOOL_VERSION: 1.10.0
  ARTIFACT_TAG: ${{ github.sha }}
  TEST_DB_HOST: 127.0.0.1
  TEST_DB_PORT: 3306
  TEST_DB_USERNAME: root
  TEST_DB_PASSWORD: 12345678

jobs:
  setup_proto:
    name: Setup Proto
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./proto

    strategy:
      matrix:
        os: [ubuntu-latest]
        golang: ['^1.16.7']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Golang ${{ matrix.golang }}
        uses: actions/setup-go@v2

      - name: Install protobuf
        run: |
          curl -fSLO https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/* /usr/local/bin/
          sudo mv protoc/include/* /usr/local/include/
          sudo chmod +x /usr/local/bin/protoc
          sudo chmod +x /usr/local/include/google

      - name: Install prototool
        run: |
          curl -fSLO "https://github.com/uber/prototool/releases/download/v${PROTOTOOL_VERSION}/prototool-$(uname -s)-$(uname -m)"
          sudo mv ./prototool-$(uname -s)-$(uname -m) /usr/local/bin/prototool
          sudo chmod +x /usr/local/bin/prototool

      - name: Install gRPC tools
        run: |
          export GOPATH=$(go env GOPATH)
          make install

      - name: Generate proto
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          make protoc
          make generate SERVICE_PATH='./../api/server/book'

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${ARTIFACT_TAG}
          path: api/server/book/proto

  build_and_test:
    name: Build and Test
    needs: setup_proto
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./api/server/book

    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        golang: ['^1.15.6']

    services:
      db:
        image: mysql:8.0.23
        ports:
          - 33060:3306
        options: |
          -v ./../../../infra/mysql/test.conf:/etc/mysql/conf.d/my.cnf
          -v ./../../../infra/mysql/sql:/docker-entrypoint-initdb.d
        env:
          MYSQL_ROOT_PASSWORD: 12345678

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Golang ${{ matrix.golang }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}

      - name: Download artifact for setup proto
        uses: actions/download-artifact@v2
        with:
          name: artifact-${ARTIFACT_TAG}
          path: api/server/book/proto

      - name: Check golang version
        run: go version

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Setup
        run: make setup

      - name: Fmt
        run: make fmt

      - name: Vet
        run: make vet

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make build
