name: Frontend(Native) Build and Test

on:
  push:
    paths:
      - '.github/workflows/ci-native-for-all.yaml'
      - 'native/**'

env:
  PROTOBUF_VERSION: 3.9.0
  PROTOTOOL_VERSION: 1.10.0
  ARTIFACT_TAG: ${{ github.sha }}
  RAKUTEN_BOOKS_APPLICATION_ID: ${{ secrets.RAKUTEN_BOOKS_APPLICATION_ID }}

jobs:
  setup_proto:
    name: Setup Proto
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: .

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Container build
        run: docker-compose -f docker-compose.ci.yaml build proto

      - name: Generate proto
        run: docker-compose -f docker-compose.ci.yaml run --rm proto make build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${ARTIFACT_TAG}
          path: native/app/types/api

  build_and_test:
    name: Build and Test
    needs: setup_proto
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./native

    strategy:
      matrix:
        os: [ubuntu-latest] # exclude: macos-latest, windows-latest
        node: [16.1]
        expo: ['4.x']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Download artifact for setup proto
        uses: actions/download-artifact@v2
        with:
          name: artifact-${ARTIFACT_TAG}
          path: native/app/types/api

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn --check-files --frozen-lockfile --non-interactive

      # - name: Protoc
      #   run: yarn protoc

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          flags: native
          verbose: true

      # - name: Use Expo ${{ matrix.expo }}
      #   uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: ${{ matrix.expo }}
      #     expo-username: ${{ secrets.STG_EXPO_CLI_USERNAME }}
      #     expo-password: ${{ secrets.STG_EXPO_CLI_PASSWORD }}

      # - name: Build iOS
      #   run: expo build:ios -t simulator

      # - name: Build Android
      #   run: expo build:android -t app-bundle
