name: Proto Test

on:
  push:
    paths:
      - '.github/workflows/ci-proto-for-all.yaml'
      - 'proto/**'

env:
  PROTOTOOL_VERSION: 1.10.0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: ./proto

    strategy:
      matrix:
        os: [ubuntu-latest]
        golang: ['^1.16.3']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Golang ${{ matrix.golang }}
        uses: actions/setup-go@v2

      - name: Export environment
        run: |
          export GOPATH="$(go env GOPATH)"
          export PATH="$PATH:${GOPATH}/bin"

      - name: Configure prototool
        run: |
          curl -fSLO "https://github.com/uber/prototool/releases/download/v${PROTOTOOL_VERSION}/prototool-$(uname -s)-$(uname -m)"
          sudo mv ./prototool-$(uname -s)-$(uname -m) /usr/local/bin/prototool
          sudo chmod +x /usr/local/bin/prototool

      - name: Install Libraries
        run: make install

      - name: Lint
        run: make format
