name: Pull Request Labeler (Approved)
on:
- pull_request_review

env:
  APPROVALS: 1
  ADD_LABEL: mergeable

jobs:
  label_when_approved:
    name: label when approved
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: pullreminders/label-when-approved-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPROVALS: ${APPROVALS}
        ADD_LABEL: ${ADD_LABEL}
