name: Pull Request Auto Assign Reviewer
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add_reviewers:
    name: auto assign reviewers
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: kentaro-m/auto-assign-action@master
        with:
          configuration-path: .github/reviewer.yaml
